
async function loadFeesPage(){
 const role=getSessionRole(); const a=document.getElementById('feesAdminPanel'),p=document.getElementById('feesParentPanel'),l=document.getElementById('feesLearnerPanel'); if(!a)return; [a,p,l].forEach(x=>x.style.display='none');
 if(role==='admin'||role==='teacher'){a.style.display='block'; await loadFeeSchoolSelectV46(); await loadSchoolFeesV46();}
 if(role==='parent'){p.style.display='block'; await loadParentFeeChildrenV46();}
 if(role==='learner'){l.style.display='block'; await loadLearnerFeesV46();}
}
async function loadFeeSchoolSelectV46(){const sel=document.getElementById('feesSchoolSelect');if(!sel)return;try{const r=await fetch('/api/schools/mine',{credentials:'include'}),d=await r.json();if(!r.ok)throw new Error(d.error||'Could not load school access.');const schools=d.schools||[];sel.innerHTML=schools.map(x=>`<option value="${escHtml(x.schoolId)}">${escHtml(x.schoolName)}</option>`).join('')||'<option value="">No school workspace</option>';sel.onchange=loadSchoolFeesV46}catch(e){sel.innerHTML='<option value="">Could not load school</option>';showToast?.(e.message,'error')}}
async function loadSchoolFeesV46(){const sid=document.getElementById('feesSchoolSelect')?.value;if(!sid)return;try{const r=await fetch('/api/schools/fees?schoolId='+encodeURIComponent(sid),{credentials:'include'}),d=await r.json();if(!r.ok)throw new Error(d.error||'Could not load fees.');document.getElementById('feeAccountsRows').innerHTML=(d.accounts||[]).map(x=>`<tr><td>${escHtml(x.learnerEmail)}</td><td>KES ${Number(x.charges||0).toLocaleString()}</td><td>KES ${Number(x.paid||0).toLocaleString()}</td><td><b>KES ${Number(x.balance||0).toLocaleString()}</b></td></tr>`).join('')||'<tr><td colspan="4">No fee accounts yet.</td></tr>';document.getElementById('feeChargesRows').innerHTML=(d.charges||[]).map(x=>`<tr><td>${escHtml(x.learnerEmail)}</td><td>${escHtml(x.feeName)}</td><td>KES ${Number(x.amount||0).toLocaleString()}</td><td>${escHtml(x.dueDate||'—')}</td><td>${escHtml(x.status)}</td></tr>`).join('')||'<tr><td colspan="5">No charges yet.</td></tr>';document.getElementById('feePaymentsRows').innerHTML=(d.payments||[]).map(x=>`<tr><td>${escHtml(x.learnerEmail)}</td><td>KES ${Number(x.amount||0).toLocaleString()}</td><td>${escHtml(x.method)}</td><td>${escHtml(x.reference||'—')}</td><td>${escHtml(x.paidAt||'—')}</td></tr>`).join('')||'<tr><td colspan="5">No payments recorded.</td></tr>'}catch(e){showToast?.(e.message,'error')}}
async function createFeeChargeV46(){const sid=document.getElementById('feesSchoolSelect')?.value,payload={schoolId:sid,learnerEmail:document.getElementById('feeLearnerEmail')?.value,feeName:document.getElementById('feeName')?.value,amount:Number(document.getElementById('feeAmount')?.value),dueDate:document.getElementById('feeDueDate')?.value,classId:document.getElementById('feeClassId')?.value};try{const r=await fetch('/api/schools/fees/charges',{method:'POST',headers:{'Content-Type':'application/json'},credentials:'include',body:JSON.stringify(payload)}),d=await r.json();if(!r.ok)throw new Error(d.error||'Could not create fee charge.');showToast?.('Fee charge created.','success');loadSchoolFeesV46()}catch(e){showToast?.(e.message,'error')}}
async function recordFeePaymentV46(){const sid=document.getElementById('feesSchoolSelect')?.value,payload={schoolId:sid,learnerEmail:document.getElementById('feePaymentLearner')?.value,amount:Number(document.getElementById('feePaymentAmount')?.value),method:document.getElementById('feePaymentMethod')?.value,reference:document.getElementById('feePaymentReference')?.value};try{const r=await fetch('/api/schools/fees/payments',{method:'POST',headers:{'Content-Type':'application/json'},credentials:'include',body:JSON.stringify(payload)}),d=await r.json();if(!r.ok)throw new Error(d.error||'Could not record payment.');showToast?.('Payment recorded.','success');loadSchoolFeesV46()}catch(e){showToast?.(e.message,'error')}}
async function loadParentFeeChildrenV46(){const sel=document.getElementById('parentFeeChild');try{const r=await fetch('/api/parent/children',{credentials:'include'}),d=await r.json();if(!r.ok)throw new Error(d.error||'Could not load linked learners.');sel.innerHTML=(d.children||[]).map(x=>`<option value="${escHtml(x.learnerEmail)}">${escHtml(x.learnerEmail)}${x.className?' — '+escHtml(x.className):''}</option>`).join('')||'<option value="">No linked learners</option>';await loadParentFeesV46()}catch(e){sel.innerHTML='<option value="">Could not load learners</option>';showToast?.(e.message,'error')}}
async function loadParentFeesV46(){const learner=document.getElementById('parentFeeChild')?.value;if(!learner)return;try{const r=await fetch('/api/parent/fees?learnerEmail='+encodeURIComponent(learner),{credentials:'include'}),d=await r.json();if(!r.ok)throw new Error(d.error||'Could not load fee account.');document.getElementById('parentFeeBilled').textContent='KES '+Number(d.summary?.billed||0).toLocaleString();document.getElementById('parentFeePaid').textContent='KES '+Number(d.summary?.paid||0).toLocaleString();document.getElementById('parentFeeBalance').textContent='KES '+Number(d.summary?.balance||0).toLocaleString();document.getElementById('parentFeeChargesRows').innerHTML=(d.charges||[]).map(x=>`<tr><td>${escHtml(x.feeName)}</td><td>KES ${Number(x.amount||0).toLocaleString()}</td><td>${escHtml(x.dueDate||'—')}</td><td>${escHtml(x.status)}</td></tr>`).join('')||'<tr><td colspan="4">No fee charges.</td></tr>';document.getElementById('parentFeePaymentsRows').innerHTML=(d.payments||[]).map(x=>`<tr><td>KES ${Number(x.amount||0).toLocaleString()}</td><td>${escHtml(x.method)}</td><td>${escHtml(x.reference||'—')}</td><td>${escHtml(x.paidAt||'—')}</td></tr>`).join('')||'<tr><td colspan="4">No payments recorded.</td></tr>'}catch(e){showToast?.(e.message,'error')}}
async function loadLearnerFeesV46(){try{const r=await fetch('/api/learner/fees',{credentials:'include'}),d=await r.json();if(!r.ok)throw new Error(d.error||'Could not load fee account.');document.getElementById('learnerFeeBilled').textContent='KES '+Number(d.summary?.billed||0).toLocaleString();document.getElementById('learnerFeePaid').textContent='KES '+Number(d.summary?.paid||0).toLocaleString();document.getElementById('learnerFeeBalance').textContent='KES '+Number(d.summary?.balance||0).toLocaleString();document.getElementById('learnerFeeChargesRows').innerHTML=(d.charges||[]).map(x=>`<tr><td>${escHtml(x.feeName)}</td><td>KES ${Number(x.amount||0).toLocaleString()}</td><td>${escHtml(x.dueDate||'—')}</td><td>${escHtml(x.status)}</td></tr>`).join('')||'<tr><td colspan="4">No fee charges.</td></tr>'}catch(e){showToast?.(e.message,'error')}}
