
function attendanceToday(){return new Date().toISOString().slice(0,10)}
async function loadAttendance(){
  const role=getSessionRole();
  const tp=document.getElementById('attendanceTeacherPanel'), lp=document.getElementById('attendanceLearnerPanel'), pp=document.getElementById('attendanceParentPanel'), af=document.getElementById('calendarAdminForm');
  if(!tp)return;
  tp.style.display=['teacher','admin'].includes(role)?'block':'none'; lp.style.display=role==='learner'?'block':'none'; pp.style.display=role==='parent'?'block':'none'; af.style.display=role==='admin'?'block':'none';
  const date=document.getElementById('attendanceDate'); if(date&&!date.value)date.value=attendanceToday();
  if(role==='teacher'||role==='admin')await loadAttendanceRegister();
  if(role==='learner')await loadLearnerAttendance();
  if(role==='parent')await loadParentAttendanceChildren();
  await loadSchoolCalendar();
}
async function loadAttendanceRegister(){
  const date=document.getElementById('attendanceDate')?.value||attendanceToday(), box=document.getElementById('attendanceRegisterRows'); if(!box)return;
  box.innerHTML='<tr><td colspan="4">Loading…</td></tr>';
  try{const r=await fetch('/api/schools/attendance?date='+encodeURIComponent(date),{credentials:'include'}),d=await r.json();if(!r.ok)throw new Error(d.error||'Could not load attendance.');window.attendanceRows=d.rows||[];box.innerHTML=window.attendanceRows.length?window.attendanceRows.map((x,i)=>`<tr data-attendance-index="${i}"><td>${escHtml(x.learnerEmail)}</td><td>${escHtml(x.className||'—')}</td><td><select class="attendance-status"><option value="present" ${x.status==='present'?'selected':''}>Present</option><option value="absent" ${x.status==='absent'?'selected':''}>Absent</option><option value="late" ${x.status==='late'?'selected':''}>Late</option><option value="excused" ${x.status==='excused'?'selected':''}>Excused</option></select></td><td><input class="attendance-note" maxlength="300" value="${escHtml(x.note||'')}" placeholder="Optional note"></td></tr>`).join(''):'<tr><td colspan="4">No learners are assigned to your school/class.</td></tr>'}catch(e){box.innerHTML=`<tr><td colspan="4">${escHtml(e.message)}</td></tr>`}
}
function markAllAttendance(status){document.querySelectorAll('#attendanceRegisterRows .attendance-status').forEach(x=>x.value=status)}
async function saveAttendanceRegister(){
  const rows=[...document.querySelectorAll('#attendanceRegisterRows tr[data-attendance-index]')]; const date=document.getElementById('attendanceDate')?.value||attendanceToday(); const entries=rows.map(r=>{const i=Number(r.dataset.attendanceIndex),x=window.attendanceRows?.[i];return x?{learnerEmail:x.learnerEmail,classId:x.classId,status:r.querySelector('.attendance-status')?.value||'present',note:r.querySelector('.attendance-note')?.value||''}:null}).filter(Boolean);
  if(!entries.length){showToast?.('There are no attendance records to save.','info');return}
  try{const r=await fetch('/api/schools/attendance',{method:'POST',headers:{'Content-Type':'application/json'},credentials:'include',body:JSON.stringify({date,entries})}),d=await r.json();if(!r.ok)throw new Error(d.error||'Could not save attendance.');showToast?.('Attendance saved successfully.','success');loadAttendanceRegister()}catch(e){showToast?.(e.message,'error')}
}
async function loadLearnerAttendance(){try{const r=await fetch('/api/learner/attendance',{credentials:'include'}),d=await r.json();if(!r.ok)throw new Error(d.error||'Could not load attendance.');document.getElementById('learnerAttendanceRate').textContent=(d.summary?.attendancePercent??0)+'%';document.getElementById('learnerAttendanceDays').textContent=d.summary?.total||0;document.getElementById('learnerAttendanceRows').innerHTML=(d.rows||[]).length?d.rows.map(x=>`<tr><td>${escHtml(x.attendanceDate)}</td><td>${escHtml(x.className||'—')}</td><td>${escHtml(x.status)}</td><td>${escHtml(x.note||'')}</td></tr>`).join(''):'<tr><td colspan="4">No attendance records yet.</td></tr>'}catch(e){document.getElementById('learnerAttendanceRows').innerHTML=`<tr><td colspan="4">${escHtml(e.message)}</td></tr>`}}
async function loadParentAttendanceChildren(){
  const sel=document.getElementById('attendanceParentChild'); if(!sel)return;
  try{const r=await fetch('/api/parent/children',{credentials:'include'}),d=await r.json();if(!r.ok)throw new Error(d.error||'Could not load linked learners.');sel.innerHTML=(d.children||[]).map(x=>`<option value="${escHtml(x.learnerEmail)}">${escHtml(x.learnerEmail)}${x.className?' — '+escHtml(x.className):''}</option>`).join('')||'<option value="">No linked learners</option>';await loadParentAttendance()}catch(e){sel.innerHTML='<option value="">Could not load learners</option>';document.getElementById('parentAttendanceRows').innerHTML=`<tr><td colspan="5">${escHtml(e.message)}</td></tr>`}}
async function loadParentAttendance(){const learner=document.getElementById('attendanceParentChild')?.value;if(!learner)return;try{const r=await fetch('/api/parent/attendance?learnerEmail='+encodeURIComponent(learner),{credentials:'include'}),d=await r.json();if(!r.ok)throw new Error(d.error||'Could not load attendance.');document.getElementById('parentAttendanceRate').textContent=(d.summary?.attendancePercent??0)+'%';document.getElementById('parentAttendanceDays').textContent=d.summary?.total||0;document.getElementById('parentAttendanceRows').innerHTML=(d.rows||[]).length?d.rows.map(x=>`<tr><td>${escHtml(x.attendanceDate)}</td><td>${escHtml(x.schoolName||'—')}</td><td>${escHtml(x.className||'—')}</td><td>${escHtml(x.status)}</td><td>${escHtml(x.note||'')}</td></tr>`).join(''):'<tr><td colspan="5">No attendance records yet.</td></tr>'}catch(e){document.getElementById('parentAttendanceRows').innerHTML=`<tr><td colspan="5">${escHtml(e.message)}</td></tr>`}}
async function loadSchoolCalendar(){const box=document.getElementById('schoolCalendarRows');if(!box)return;try{const r=await fetch('/api/schools/calendar',{credentials:'include'}),d=await r.json();if(!r.ok)throw new Error(d.error||'Could not load school calendar.');box.innerHTML=(d.events||[]).length?d.events.map(x=>`<tr><td>${escHtml(x.eventDate)}${x.endDate&&x.endDate!==x.eventDate?' → '+escHtml(x.endDate):''}</td><td><b>${escHtml(x.title)}</b></td><td>${escHtml(x.eventType)}</td><td>${escHtml(x.description||'')}</td><td>${getSessionRole()==='admin'?`<button class="btn" onclick="deleteSchoolCalendarEvent('${escHtml(x.eventId)}')">Delete</button>`:'—'}</td></tr>`).join(''):'<tr><td colspan="5">No calendar events yet.</td></tr>'}catch(e){box.innerHTML=`<tr><td colspan="5">${escHtml(e.message)}</td></tr>`}}
async function createSchoolCalendarEvent(){const payload={title:document.getElementById('calendarTitle')?.value||'',description:document.getElementById('calendarDescription')?.value||'',eventDate:document.getElementById('calendarStart')?.value||'',endDate:document.getElementById('calendarEnd')?.value||'',eventType:document.getElementById('calendarType')?.value||'school'};try{const r=await fetch('/api/schools/calendar',{method:'POST',headers:{'Content-Type':'application/json'},credentials:'include',body:JSON.stringify(payload)}),d=await r.json();if(!r.ok)throw new Error(d.error||'Could not create event.');document.getElementById('calendarTitle').value='';document.getElementById('calendarDescription').value='';showToast?.('Calendar event added.','success');loadSchoolCalendar()}catch(e){showToast?.(e.message,'error')}}
async function deleteSchoolCalendarEvent(id){if(!confirm('Delete this calendar event?'))return;try{const r=await fetch('/api/schools/calendar/'+encodeURIComponent(id),{method:'DELETE',credentials:'include'}),d=await r.json();if(!r.ok)throw new Error(d.error||'Could not delete event.');loadSchoolCalendar()}catch(e){showToast?.(e.message,'error')}}
