
let timetableData={school:null,periods:[],entries:[],classes:[],subjects:[],teachers:[]};
const ttDays={1:'Monday',2:'Tuesday',3:'Wednesday',4:'Thursday',5:'Friday',6:'Saturday',7:'Sunday'};
async function loadTimetable(){
  const sel=document.getElementById('ttSchoolSelect'); if(!sel)return;
  try{
    let schools=[]; const role=getSessionRole();
    if(role==='parent'){const r=await fetch('/api/parent/children',{credentials:'include'}),d=await r.json();if(!r.ok)throw new Error(d.error||'Could not load linked schools.');schools=(d.children||[]).map(x=>({schoolId:x.schoolId,schoolName:x.schoolName,memberRole:'parent'})).filter((x,i,a)=>a.findIndex(y=>y.schoolId===x.schoolId)===i)}
    else {const r=await fetch('/api/schools/mine',{credentials:'include'}),d=await r.json();if(!r.ok)throw new Error(d.error||'Could not load school access.');schools=d.schools||[];}
    if(role==='admin'&&!schools.length){const r=await fetch('/api/admin/schools',{credentials:'include'});if(r.ok){const d=await r.json();schools=(d.schools||[]).filter(x=>x.status==='active').map(x=>({schoolId:x.schoolId,schoolName:x.schoolName,memberRole:'admin'}));}}
    const current=sel.value; sel.innerHTML=schools.length?schools.map(x=>`<option value="${escHtml(x.schoolId)}">${escHtml(x.schoolName)} — ${escHtml(x.memberRole||'member')}</option>`).join(''):'<option value="">No school access</option>'; if(current&&schools.some(x=>x.schoolId===current))sel.value=current;
    if(!sel.value){renderTimetable();return}
    const r=await fetch('/api/schools/timetable?schoolId='+encodeURIComponent(sel.value),{credentials:'include'}),d=await r.json();if(!r.ok)throw new Error(d.error||'Could not load timetable.');timetableData=d;
    const canEdit=role==='admin'||(schools.find(x=>x.schoolId===sel.value)?.memberRole==='admin');document.getElementById('ttAdminPanel').style.display=canEdit?'block':'none';
    fillTimetableForms(); renderTimetable();
  }catch(e){showToast?.(e.message,'error');document.getElementById('ttGrid').innerHTML=`<div class="notice" style="grid-column:1/-1">${escHtml(e.message)}</div>`}
}
function fillTimetableForms(){
  const set=(id,html)=>{const e=document.getElementById(id);if(e)e.innerHTML=html};
  set('ttClass','<option value="">Select class</option>'+timetableData.classes.map(x=>`<option value="${escHtml(x.classId)}">${escHtml(x.className)}</option>`).join(''));
  set('ttSubject','<option value="">Select subject</option>'+timetableData.subjects.map(x=>`<option value="${escHtml(x.subjectId)}">${escHtml(x.subjectName)}</option>`).join(''));
  set('ttTeacher','<option value="">Select teacher</option>'+timetableData.teachers.map(x=>`<option value="${escHtml(x.email)}">${escHtml(x.email)}</option>`).join(''));
  const view=document.getElementById('ttView')?.value||'class', filter=document.getElementById('ttFilter');if(filter){let vals=[];if(view==='class')vals=timetableData.classes.map(x=>[x.classId,x.className]);if(view==='teacher')vals=timetableData.teachers.map(x=>[x.email,x.email]);if(view==='room')vals=[...new Set(timetableData.entries.map(x=>x.room).filter(Boolean))].map(x=>[x,x]);filter.innerHTML='<option value="">All</option>'+vals.map(x=>`<option value="${escHtml(x[0])}">${escHtml(x[1])}</option>`).join('')}}
function renderTimetable(){
  const view=document.getElementById('ttView')?.value||'class', filter=document.getElementById('ttFilter')?.value||'';fillTimetableForms();
  let rows=timetableData.entries||[];if(view==='class'&&filter)rows=rows.filter(x=>x.classId===filter);if(view==='teacher'&&filter)rows=rows.filter(x=>x.teacherEmail===filter);if(view==='room'&&filter)rows=rows.filter(x=>x.room===filter);
  const periodMap=new Map((timetableData.periods||[]).map(x=>[`${x.dayOfWeek}-${x.periodNo}`,x]));
  document.getElementById('ttSummary').innerHTML=`<div class="card"><small>Lessons</small><p><b>${rows.length}</b></p></div><div class="card"><small>Published</small><p><b>${rows.filter(x=>x.status==='published').length}</b></p></div><div class="card"><small>Classes</small><p><b>${new Set(rows.map(x=>x.classId)).size}</b></p></div><div class="card"><small>Teachers</small><p><b>${new Set(rows.map(x=>x.teacherEmail).filter(Boolean)).size}</b></p></div>`;
  const grid=document.getElementById('ttGrid');grid.innerHTML='';for(let day=1;day<=5;day++){const col=document.createElement('div');col.className='tt-day';col.innerHTML=`<h4>${ttDays[day]}</h4>`;const dayPeriods=(timetableData.periods||[]).filter(p=>p.dayOfWeek===day).sort((a,b)=>a.periodNo-b.periodNo);const nums=[...new Set([...dayPeriods.map(p=>p.periodNo),...rows.filter(x=>x.dayOfWeek===day).map(x=>x.periodNo)])].sort((a,b)=>a-b);if(!nums.length)col.innerHTML+=`<div class="small">No periods configured.</div>`;nums.forEach(no=>{const p=periodMap.get(`${day}-${no}`);const cell=document.createElement('div');cell.className='tt-slot'+(p&&p.kind!=='lesson'?' break':'');const lessons=rows.filter(x=>x.dayOfWeek===day&&x.periodNo===no);cell.innerHTML=`<small>${escHtml(p?.label||('Period '+no))}${p?.startsAt?' · '+escHtml(String(p.startsAt).slice(0,5)):''}</small>`+(lessons.length?lessons.map(x=>`<b>${escHtml(x.subjectName||x.title||'Lesson')}</b><span class="small">${view==='class'?escHtml(x.teacherEmail||'Teacher'):escHtml(x.className||'Class')}${x.room?' · '+escHtml(x.room):''}</span>`).join(''):'<span class="small">Free</span>');col.appendChild(cell)});grid.appendChild(col)}
  const canEdit=document.getElementById('ttAdminPanel')?.style.display!=='none';document.getElementById('ttRows').innerHTML=rows.length?rows.map(x=>`<tr><td>${escHtml(ttDays[x.dayOfWeek]||x.dayOfWeek)}</td><td>${x.periodNo}</td><td>${escHtml(x.className)}</td><td>${escHtml(x.subjectName||x.title||'—')}</td><td>${escHtml(x.teacherEmail||'—')}</td><td>${escHtml(x.room||'—')}</td><td><span class="tag">${escHtml(x.status)}</span></td><td>${canEdit?`<button class="btn" onclick="deleteTimetableEntry('${escHtml(x.entryId)}')">Delete</button>`:'—'}</td></tr>`).join(''):'<tr><td colspan="8">No timetable lessons yet.</td></tr>';
}
async function addTimetablePeriod(){const schoolId=document.getElementById('ttSchoolSelect').value;const body={schoolId,dayOfWeek:Number(ttPeriodDay.value),periodNo:Number(ttPeriodNo.value),label:ttPeriodLabel.value,kind:ttPeriodKind.value,startsAt:ttStartsAt.value,endsAt:ttEndsAt.value};try{const r=await fetch('/api/schools/timetable/periods',{method:'POST',headers:{'Content-Type':'application/json'},credentials:'include',body:JSON.stringify(body)}),d=await r.json();if(!r.ok)throw new Error(d.error||'Could not save period.');showToast?.('Period saved.','success');await loadTimetable()}catch(e){showToast?.(e.message,'error')}}
async function addTimetableEntry(){const schoolId=document.getElementById('ttSchoolSelect').value;const body={schoolId,classId:ttClass.value,subjectId:ttSubject.value,teacherEmail:ttTeacher.value,dayOfWeek:Number(ttEntryDay.value),periodNo:Number(ttEntryNo.value),room:ttRoom.value,title:ttEntryTitle.value};try{const r=await fetch('/api/schools/timetable/entries',{method:'POST',headers:{'Content-Type':'application/json'},credentials:'include',body:JSON.stringify(body)}),d=await r.json();if(!r.ok)throw new Error(d.error||'Could not add lesson.');showToast?.('Lesson added to draft timetable.','success');await loadTimetable()}catch(e){showToast?.(e.message,'error')}}
async function deleteTimetableEntry(id){const schoolId=document.getElementById('ttSchoolSelect').value;try{const r=await fetch('/api/schools/timetable/entries/'+encodeURIComponent(id),{method:'DELETE',headers:{'Content-Type':'application/json'},credentials:'include',body:JSON.stringify({schoolId})}),d=await r.json();if(!r.ok)throw new Error(d.error||'Could not delete lesson.');await loadTimetable();showToast?.('Lesson deleted.','success')}catch(e){showToast?.(e.message,'error')}}
async function publishTimetable(status){const schoolId=document.getElementById('ttSchoolSelect').value;try{const r=await fetch('/api/schools/timetable/publish',{method:'PATCH',headers:{'Content-Type':'application/json'},credentials:'include',body:JSON.stringify({schoolId,status})}),d=await r.json();if(!r.ok)throw new Error(d.error||'Could not update timetable status.');showToast?.(status==='published'?'Timetable published.':'Timetable returned to draft.','success');await loadTimetable()}catch(e){showToast?.(e.message,'error')}}

async function loadPersonalizedLearning(){
  try{const r=await fetch('/api/learner/personalized',{credentials:'include'}),d=await r.json();if(!r.ok)throw new Error(d.error||'Could not load recommendations.');const p=d.preferences||{};document.getElementById('prefSubject').value=p.preferredSubject||'';document.getElementById('prefGrade').value=p.preferredGrade||'';document.getElementById('prefTopics').value=p.focusTopics||'';document.getElementById('prefMinutes').value=p.dailyMinutes||30;document.getElementById('personalizedReason').textContent=d.reason||'';const rec=document.getElementById('personalizedRecommendations');rec.innerHTML=(d.recommendations||[]).map(x=>`<div class="recommendation-card"><b>${escHtml(x.title)}</b><div class="small">${escHtml(x.subject||'General')} · ${escHtml(x.grade||'All grades')} ${x.topic?'· '+escHtml(x.topic):''}</div><p class="small">${escHtml(x.description||'Digital learning resource')}</p><button class="btn" onclick="openRecommendedPersonalized('${escHtml(x.id)}')">Open Resource</button></div>`).join('')||'<p>No matching resources yet. Try a different subject or grade.</p>';document.getElementById('personalizedRecent').innerHTML=(d.recent||[]).slice(0,8).map(x=>`<div class="progress-row"><div><b>${escHtml(x.title)}</b><br><small>${escHtml(x.subject||'General')} · ${x.viewCount||0} view(s)</small></div><span class="tag">${x.bookmarked?'🔖 Saved':'Viewed'}</span></div>`).join('')||'<p>No learning activity recorded yet.</p>';}catch(e){showToast?.(e.message,'error')}}
async function savePersonalizedPreferences(){try{const body={preferredSubject:document.getElementById('prefSubject').value,preferredGrade:document.getElementById('prefGrade').value,focusTopics:document.getElementById('prefTopics').value,dailyMinutes:document.getElementById('prefMinutes').value};const r=await fetch('/api/learner/personalized/preferences',{method:'PATCH',headers:{'Content-Type':'application/json'},credentials:'include',body:JSON.stringify(body)}),d=await r.json();if(!r.ok)throw new Error(d.error||'Could not save preferences.');document.getElementById('prefStatus').textContent='Preferences saved.';showToast?.('Learning preferences saved.','success');loadPersonalizedLearning()}catch(e){showToast?.(e.message,'error')}}
function openRecommendedPersonalized(id){const m=(materials||[]).find(x=>String(x.id)===String(id));if(m){handleMaterialButton(id);return}show('digitalLibrary');loadDigitalLibrary?.()}

async function loadLearnerPortfolio(){
  try{
    const [pr,ar]=await Promise.all([fetch('/api/learner/portfolio',{credentials:'include'}),fetch('/api/learner/achievements',{credentials:'include'})]);
    const p=await pr.json(), a=await ar.json();
    if(!pr.ok) throw new Error(p.error||'Could not load portfolio.');
    if(!ar.ok) throw new Error(a.error||'Could not load achievements.');
    const stats=a.stats||{};
    const statDefs=[['Materials viewed',stats.materialsViewed||0],['Bookmarks',stats.bookmarks||0],['Assignments',stats.assignmentsSubmitted||0],['Discussions',stats.discussions||0],['Verified work',stats.verifiedPortfolio||0],['Certificates',stats.certificates||0]];
    document.getElementById('achievementStats').innerHTML=statDefs.map(x=>`<div class="card"><b>${x[1]}</b><small>${escapeHtml(x[0])}</small></div>`).join('');
    const badges=a.badges||[], earned=badges.filter(b=>b.earned).length;
    document.getElementById('achievementBadgeCount').textContent=`${earned} of ${badges.length} badges earned`;
    document.getElementById('achievementBadges').innerHTML=badges.map(b=>`<div class="card" style="opacity:${b.earned?1:.55}"><div style="font-size:28px">${b.icon}</div><b>${escapeHtml(b.name)}</b><p class="small">${escapeHtml(b.description)}</p><strong>${b.earned?'✓ Earned':'Not yet earned'}</strong></div>`).join('');
    document.getElementById('portfolioItems').innerHTML=(p.items||[]).length?(p.items||[]).map(x=>`<div class="card"><div class="topline"><b>${escapeHtml(x.title)}</b><span class="badge">${escapeHtml(x.status||'pending')}</span></div><small>${escapeHtml(x.category)}</small><p>${escapeHtml(x.description||'No description provided.')}</p>${x.evidenceUrl?`<a href="${escapeHtml(x.evidenceUrl)}" target="_blank" rel="noopener noreferrer">Open evidence</a>`:''}${x.reviewerFeedback?`<p class="notice">Teacher/Admin feedback: ${escapeHtml(x.reviewerFeedback)}</p>`:''}<button class="btn" style="margin-top:8px" onclick="deletePortfolioItem(${Number(x.portfolioId)})">Delete</button></div>`).join(''):'<div class="notice">No portfolio items yet.</div>';
    document.getElementById('portfolioCertificates').innerHTML=(p.certificates||[]).length?(p.certificates||[]).map(x=>`<div class="card"><h4>${escapeHtml(x.title)}</h4><p>${escapeHtml(x.description||'Digital certificate')}</p><p class="small">Issued by ${escapeHtml(x.issuerName||'Tusome EduShelf')} · ${x.issuedAt?new Date(x.issuedAt).toLocaleDateString():''}</p><b>Verification ID: ${escapeHtml(x.verificationCode)}</b></div>`).join(''):'<div class="notice">No certificates yet.</div>';
  }catch(e){showToast?.(e.message,'error');}
}
async function addPortfolioItem(){
  const body={title:document.getElementById('portfolioTitle').value.trim(),category:document.getElementById('portfolioCategory').value,description:document.getElementById('portfolioDescription').value.trim(),evidenceUrl:document.getElementById('portfolioEvidenceUrl').value.trim()};
  if(!body.title){showToast?.('Add a portfolio title first.','error');return;}
  try{const r=await fetch('/api/learner/portfolio',{method:'POST',headers:{'Content-Type':'application/json'},credentials:'include',body:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw new Error(d.error||'Could not save portfolio item.');document.getElementById('portfolioTitle').value='';document.getElementById('portfolioDescription').value='';document.getElementById('portfolioEvidenceUrl').value='';showToast?.('Portfolio item saved.','success');loadLearnerPortfolio();}catch(e){showToast?.(e.message,'error');}
}
async function deletePortfolioItem(id){if(!confirm('Delete this portfolio item?'))return;try{const r=await fetch('/api/learner/portfolio/'+encodeURIComponent(id),{method:'DELETE',credentials:'include'});const d=await r.json();if(!r.ok)throw new Error(d.error||'Could not delete item.');loadLearnerPortfolio();}catch(e){showToast?.(e.message,'error');}}
